name: CI & Regression Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  regression:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install flask flask-cors pillow openai vtracer cairosvg python-dotenv
          pip install pytest requests pillow
      - name: Start server
        run: |
          cd server
          nohup python app.py &
          sleep 5
      - name: Run regression tests
        run: |
          pytest --maxfail=1 --disable-warnings -q 